create table projects (
    id bigint generated by default as identity,        
    name varchar(255),
    description varchar(1024),
    full_text tsvector generated always as (to_tsvector('simple'::regconfig, ((COALESCE(name, ''::character varying)::text) || ' '::text) || COALESCE(description, ''::character varying)::text)) stored,
    primary key (id)
);

CREATE INDEX IF NOT EXISTS projects_full_text_idx ON projects USING GIN (full_text);